version: '3.9'

services:
  backend:
    build:
      context: .
    command: python main.py
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - redis

  frontend:
    build:
      context: .
    command: streamlit run front_end/front_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
